<?php

namespace Outhebox\Translations\Database\Seeders;

use Illuminate\Database\Seeder;
use Outhebox\Translations\Models\Language;

class LanguageSeeder extends Seeder
{
    public function run(): void
    {
        $existing = Language::query()->pluck('code');

        $new = collect($this->languages())
            ->reject(fn (array $language) => $existing->contains($language['code']))
            ->toArray();

        Language::insert($new);
    }

    public function languages(): array
    {
        return [
            [
                'code' => 'af',
                'name' => 'Afrikaans',
                'native_name' => 'Afrikaans',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'sq',
                'name' => 'Albanian',
                'native_name' => 'Shqip',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'am',
                'name' => 'Amharic',
                'native_name' => 'አማርኛ',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'ar',
                'name' => 'Arabic',
                'native_name' => 'العربية',
                'rtl' => true,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'hy',
                'name' => 'Armenian',
                'native_name' => 'Հայերեն',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'as',
                'name' => 'Assamese',
                'native_name' => 'অসমীয়া',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'ay',
                'name' => 'Aymara',
                'native_name' => 'Aymar aru',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'az',
                'name' => 'Azerbaijani',
                'native_name' => 'Azərbaycan',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'bm',
                'name' => 'Bambara',
                'native_name' => 'Bamanankan',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'eu',
                'name' => 'Basque',
                'native_name' => 'Euskara',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'be',
                'name' => 'Belarusian',
                'native_name' => 'Беларуская',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'bn',
                'name' => 'Bengali',
                'native_name' => 'বাংলা',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'bho',
                'name' => 'Bhojpuri',
                'native_name' => 'भोजपुरी',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'bs',
                'name' => 'Bosnian',
                'native_name' => 'Bosanski',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'bg',
                'name' => 'Bulgarian',
                'native_name' => 'Български',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'ca',
                'name' => 'Catalan',
                'native_name' => 'Català',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'ceb',
                'name' => 'Cebuano',
                'native_name' => 'Cebuano',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'zh',
                'name' => 'Chinese (Simplified)',
                'native_name' => '简体中文',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'zh-Hant',
                'name' => 'Chinese (Traditional)',
                'native_name' => '繁體中文',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'co',
                'name' => 'Corsican',
                'native_name' => 'Corsu',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'hr',
                'name' => 'Croatian',
                'native_name' => 'Hrvatski',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'cs',
                'name' => 'Czech',
                'native_name' => 'Čeština',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'da',
                'name' => 'Danish',
                'native_name' => 'Dansk',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'dv',
                'name' => 'Divehi',
                'native_name' => 'ދިވެހި',
                'rtl' => true,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'nl',
                'name' => 'Dutch',
                'native_name' => 'Nederlands',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'en',
                'name' => 'English',
                'native_name' => 'English',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'en-GB',
                'name' => 'English (United Kingdom)',
                'native_name' => 'English (United Kingdom)',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'en-US',
                'name' => 'English (United States)',
                'native_name' => 'English (United States)',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'eo',
                'name' => 'Esperanto',
                'native_name' => 'Esperanto',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'et',
                'name' => 'Estonian',
                'native_name' => 'Eesti',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'fil',
                'name' => 'Filipino',
                'native_name' => 'Filipino',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'fi',
                'name' => 'Finnish',
                'native_name' => 'Suomi',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'fr',
                'name' => 'French',
                'native_name' => 'Français',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'gl',
                'name' => 'Galician',
                'native_name' => 'Galego',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'ka',
                'name' => 'Georgian',
                'native_name' => 'ქართული',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'de',
                'name' => 'German',
                'native_name' => 'Deutsch',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'el',
                'name' => 'Greek',
                'native_name' => 'Ελληνικά',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'gn',
                'name' => 'Guarani',
                'native_name' => "Avañe'ẽ",
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'gu',
                'name' => 'Gujarati',
                'native_name' => 'ગુજરાતી',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'ht',
                'name' => 'Haitian Creole',
                'native_name' => 'Kreyòl Ayisyen',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'ha',
                'name' => 'Hausa',
                'native_name' => 'Hausa',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'haw',
                'name' => 'Hawaiian',
                'native_name' => 'ʻŌlelo Hawaiʻi',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'he',
                'name' => 'Hebrew',
                'native_name' => 'עברית',
                'rtl' => true,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'hi',
                'name' => 'Hindi',
                'native_name' => 'हिन्दी',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'hu',
                'name' => 'Hungarian',
                'native_name' => 'Magyar',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'is',
                'name' => 'Icelandic',
                'native_name' => 'Íslenska',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'ig',
                'name' => 'Igbo',
                'native_name' => 'Igbo',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'id',
                'name' => 'Indonesian',
                'native_name' => 'Bahasa Indonesia',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'ga',
                'name' => 'Irish',
                'native_name' => 'Gaeilge',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'it',
                'name' => 'Italian',
                'native_name' => 'Italiano',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'ja',
                'name' => 'Japanese',
                'native_name' => '日本語',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'jv',
                'name' => 'Javanese',
                'native_name' => 'Jawa',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'kn',
                'name' => 'Kannada',
                'native_name' => 'ಕನ್ನಡ',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'kk',
                'name' => 'Kazakh',
                'native_name' => 'Қазақ тілі',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'km',
                'name' => 'Khmer',
                'native_name' => 'ខ្មែរ',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'rw',
                'name' => 'Kinyarwanda',
                'native_name' => 'Ikinyarwanda',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'ko',
                'name' => 'Korean',
                'native_name' => '한국어',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'ku',
                'name' => 'Kurdish',
                'native_name' => 'Kurdî',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'ky',
                'name' => 'Kyrgyz',
                'native_name' => 'Кыргызча',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'lo',
                'name' => 'Lao',
                'native_name' => 'ລາວ',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'la',
                'name' => 'Latin',
                'native_name' => 'Latina',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'lv',
                'name' => 'Latvian',
                'native_name' => 'Latviešu',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'ln',
                'name' => 'Lingala',
                'native_name' => 'Lingála',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'lt',
                'name' => 'Lithuanian',
                'native_name' => 'Lietuvių',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'mk',
                'name' => 'Macedonian',
                'native_name' => 'Македонски',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'ms',
                'name' => 'Malay',
                'native_name' => 'Bahasa Melayu',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'ml',
                'name' => 'Malayalam',
                'native_name' => 'മലയാളം',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'mt',
                'name' => 'Maltese',
                'native_name' => 'Malti',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'mi',
                'name' => 'Maori',
                'native_name' => 'Te Reo Māori',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'mr',
                'name' => 'Marathi',
                'native_name' => 'मराठी',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'mn',
                'name' => 'Mongolian',
                'native_name' => 'Монгол',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'ne',
                'name' => 'Nepali',
                'native_name' => 'नेपाली',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'no',
                'name' => 'Norwegian',
                'native_name' => 'Norsk',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'ps',
                'name' => 'Pashto',
                'native_name' => 'پښتو',
                'rtl' => true,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'fa',
                'name' => 'Persian',
                'native_name' => 'فارسی',
                'rtl' => true,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'pl',
                'name' => 'Polish',
                'native_name' => 'Polski',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'pt',
                'name' => 'Portuguese',
                'native_name' => 'Português',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'pt-BR',
                'name' => 'Portuguese (Brazil)',
                'native_name' => 'Português (Brasil)',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'pt-PT',
                'name' => 'Portuguese (Portugal)',
                'native_name' => 'Português (Portugal)',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'pa',
                'name' => 'Punjabi',
                'native_name' => 'ਪੰਜਾਬੀ',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'ro',
                'name' => 'Romanian',
                'native_name' => 'Română',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'ru',
                'name' => 'Russian',
                'native_name' => 'Русский',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'sm',
                'name' => 'Samoan',
                'native_name' => 'Gagana Samoa',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'sr',
                'name' => 'Serbian',
                'native_name' => 'Српски',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'st',
                'name' => 'Sesotho',
                'native_name' => 'Sesotho',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'sn',
                'name' => 'Shona',
                'native_name' => 'chiShona',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'sd',
                'name' => 'Sindhi',
                'native_name' => 'سنڌي',
                'rtl' => true,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'si',
                'name' => 'Sinhala',
                'native_name' => 'සිංහල',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'sk',
                'name' => 'Slovak',
                'native_name' => 'Slovenčina',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'sl',
                'name' => 'Slovenian',
                'native_name' => 'Slovenščina',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'so',
                'name' => 'Somali',
                'native_name' => 'Soomaali',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'es',
                'name' => 'Spanish',
                'native_name' => 'Español',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'su',
                'name' => 'Sundanese',
                'native_name' => 'Basa Sunda',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'sw',
                'name' => 'Swahili',
                'native_name' => 'Kiswahili',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'sv',
                'name' => 'Swedish',
                'native_name' => 'Svenska',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'tg',
                'name' => 'Tajik',
                'native_name' => 'Тоҷикӣ',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'ta',
                'name' => 'Tamil',
                'native_name' => 'தமிழ்',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'te',
                'name' => 'Telugu',
                'native_name' => 'తెలుగు',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'th',
                'name' => 'Thai',
                'native_name' => 'ไทย',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'tr',
                'name' => 'Turkish',
                'native_name' => 'Türkçe',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'tk',
                'name' => 'Turkmen',
                'native_name' => 'Türkmen',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'uk',
                'name' => 'Ukrainian',
                'native_name' => 'Українська',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'ur',
                'name' => 'Urdu',
                'native_name' => 'اردو',
                'rtl' => true,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'uz',
                'name' => 'Uzbek',
                'native_name' => "O'zbek",
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'vi',
                'name' => 'Vietnamese',
                'native_name' => 'Tiếng Việt',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'cy',
                'name' => 'Welsh',
                'native_name' => 'Cymraeg',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'xh',
                'name' => 'Xhosa',
                'native_name' => 'isiXhosa',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'yi',
                'name' => 'Yiddish',
                'native_name' => 'ייִדיש',
                'rtl' => true,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'yo',
                'name' => 'Yoruba',
                'native_name' => 'Yorùbá',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
            [
                'code' => 'zu',
                'name' => 'Zulu',
                'native_name' => 'isiZulu',
                'rtl' => false,
                'is_source' => false,
                'tone' => 'neutral',
                'active' => false,
            ],
        ];
    }
}
